### ISSUE TITLE
[Question/Feature request] Is it possible to auto-add duedate in smart syntax?

### ISSUE THREAD

**Issue by kekwkappa** [maxpozdeev/mytinytodo#73] opened 2023-09-19 02:35 UTC
There is Smart syntax with example: +1 Task title #tag1 #tag2

Is it possible to automatically add a task due date from the task name?
Something like this: `Task title 10.10.23`   will set the duedate to October 10 this year, or any other way.

P.S.
Thank you for your project!

**Comment by maxpozdeev** [comment] 2023-09-19 11:26
Duplicate of #26

**Closed** 2023-09-19 11:26 UTC
